import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='apple-mobile-web-app-title' content='MyWebSite' />
      </head>
      <body className='min-h-dvh w-full overflow-y-scroll antialiased'>
        <main>{children}</main>
        <Toaster position='bottom-right' />
      </body>
    </html>
  );
}
