import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import '../globals.css';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import { Vazirmatn } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const vazirFont = Vazirmatn({
  style: 'normal',
  subsets: ['arabic', 'latin'],
  display: 'swap',
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<'/[locale]'>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) notFound();

  return (
    <html
      lang={locale}
      dir={locale === 'fa' ? 'rtl' : 'ltr'}
      suppressHydrationWarning
    >
      <head>
        <meta name='apple-mobile-web-app-title' content='MyWebSite' />
      </head>
      <body className={`min-h-dvh w-full ${vazirFont.className} antialiased`}>
        <ThemeProvider attribute={'class'} defaultTheme='system' enableSystem>
          <main>
            <NextIntlClientProvider>
              <NuqsAdapter>{children}</NuqsAdapter>
            </NextIntlClientProvider>
          </main>
          <Toaster position='bottom-right' />
        </ThemeProvider>
      </body>
    </html>
  );
}
