import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { Toaster } from '@/components/ui/sonner';
import { routing } from '@/i18n/routing';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import localFont from 'next/font/local';
import { notFound } from 'next/navigation';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const vazirmatnFD = localFont({
  src: [
    {
      path: '../../public/fonts/Vazirmatn-FD-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Vazirmatn-FD-SemiBold.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-vazirmatn-fd',
  display: 'swap',
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<'/[locale]'>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) notFound();

  const isFa = locale === 'fa';

  return (
    <html lang={locale} dir={isFa ? 'rtl' : 'ltr'} suppressHydrationWarning>
      <head>
        <meta name='apple-mobile-web-app-title' content='MyWebSite' />
      </head>
      <body
        className={cn(
          'min-h-dvh w-full antialiased',
          isFa && vazirmatnFD.className,
        )}
      >
        <ThemeProvider attribute={'class'} defaultTheme='system' enableSystem>
          <main>
            <NextIntlClientProvider>
              <NuqsAdapter>{children}</NuqsAdapter>
            </NextIntlClientProvider>
          </main>
          <Toaster position='bottom-right' />
        </ThemeProvider>
      </body>
    </html>
  );
}
